version: "3.5"
networks:
  gitflic:
    driver: bridge
external: false
    name: gitflic_network
services:
  web:
    container_name: gitflic_web
    build: ./gitflic/
    image: gitflic-docker/web
    command: java -jar gitflic.jar --spring.config.additional-location=file:default-config/
    restart: unless-stopped
    volumes:
      - ./gitflic/data/repo:/var/tmp/gitflic/repo
      - ./gitflic/data/img:/var/tmp/gitflic/img
      - ./gitflic/data/releases:/var/tmp/gitflic/releases
      - ./gitflic/data/cicd:/var/tmp/gitflic/cicd
      - ./gitflic/data/log:/var/tmp/gitflic/log
    environment:
      REDIS_PASS: ${REDIS_PASS}
      POSTGRES_PASS: ${POSTGRES_PASS}
      POSTGRES_USER: ${POSTGRES_USER}
      BASE_URL: ${BASE_URL}
      TRANSPORT_URL: ${TRANSPORT_URL}
      EMAIL_USER: ${EMAIL_USER}
      EMAIL_PASS: ${EMAIL_PASS}
      EMAIL_SMTP_HOST: ${EMAIL_SMTP_HOST}
      EMAIL_SMTP_PORT: ${EMAIL_SMTP_PORT}
    networks:
      - gitflic
    ports:
      - ${PORT}:8080
      - "22:22"
    depends_on:
      - postgres
      - redis
  postgres:
    container_name: gitflic_postgres
    build: ./postgres/
    image: gitflic-docker/postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASS}
      POSTGRES_DB: gitflic
    networks:
      - gitflic
  redis:
    container_name: gitflic_redis
    image: redis:7.2-alpine
    command: redis-server --requirepass ${REDIS_PASS}
    restart: unless-stopped
    networks:
      - gitflic
    volumes:
      - ./redis/data:/data
  runner:
    container_name: gitflic_runner
    build: ./runner/
    environment:
        BASE_URL: ${BASE_URL}
        PORT: ${PORT}
        TOKEN: ${TOKEN}
        DOCKER_REGISTRY_USERNAME: ${DOCKER_REGISTRY_USERNAME}
        DOCKER_REGISTRY_PASSWORD: ${DOCKER_REGISTRY_PASSWORD}
        DOCKER_REGISTRY_EMAIL: ${DOCKER_REGISTRY_EMAIL}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    network_mode: host
    restart: unless-stopped
